### ISSUE TITLE
Change official ppa?

### ISSUE THREAD

**Issue by JMoerman** [mank319/Go-For-It#101]
I created a new [ppa](https://launchpad.net/~go-for-it-team/+archive/ubuntu/go-for-it-daily) that builds packages from a bzr branch that is synced automatically with this github repository, so any change on this repo will lead to new packages being generated on the following day.

It is a team based ppa, so maintenance doesn't have a single point of failure.

Is it a good idea to make this ppa the official ppa? How do we make sure people using the current ppa will continue to have the most recent (stable) version of _Go For It!_?

**Comment by mank319** [comment]
Hi @JMoerman,

setting up a team-based PPA makes a lot of sense and I was thinking about this for quite a while already! In my opinion we should definitely make this the new, official PPA 👍 
I have contacted the Launchpad team to see if there is an official way for pointing one PPA to another so that users will receive updates transparently.

Let's wait for the response and decide the following steps then. For now, I think we should update the PPA link in the README file and on the website so that any potential new users will be subscribed to the team PPA 😉

**Comment by JMoerman** [comment]
> setting up a team-based PPA makes a lot of sense and I was thinking about this for quite a while already!

You said so two weeks ago, but you didn't respond on hangouts after that. So I went ahead and created the ppa.

As an alternative to pointing ppa:mank319/go-for-it to ppa:go-for-it-team/go-for-it-daily: you could always change your recipe to 
```
# bzr-builder format 0.3 deb-version {debupstream}-0~{revno}
lp:go-for-it
merge packaging lp:~go-for-it-team/go-for-it/packaging
```
to generate identical packages.

**Comment by mank319** [comment]
Sorry for the delayed response, @JMoerman! I currently don't have a Hangouts client installed on any of my actively used devices so I need to explicitly log into the web interface in order to see notifications...

Your proposal would be a good fallback plan if we don't hear back from the Launchpad team :-)

**Comment by JMoerman** [comment]
Any news yet?

**Comment by mank319** [comment]
Sorry I haven't heard back yet, but I will keep you updated 😉

**Comment by JMoerman** [comment]
I guess time will have to fix this issue: as users move to newer versions of Ubuntu (and Ubuntu based operating systems) they will be forced to use the new ppa.
