### ISSUE TITLE
Go-For-It is not on elementary's AppCenter

### ISSUE THREAD

**Issue by Philip-Scott** [mank319/Go-For-It#114]
Hey Manuel.

I'm not sure how active you still are, but elementary is having their own "AppCenter" where you can deploy your project right from github, without the need of PPAs. It would be really cool to see your project there :) 

If you need any help, i can gladly guide you to have it pushed there :) 

https://developer.elementary.io

**Comment by mank319** [comment]
Hi @Philip-Scott,

thanks for pointing this out!
Just to clarify, I am "inactive" because my employment contract doesn't allow me to work on side projects. @JMoerman is now the active maintainer of the project (e.g. has full write access to the repository, maintains the team PPA and all donations are forwarded to him), so he can add it to the AppCenter if he would like to 😉

**Comment by Philip-Scott** [comment]
I'll cross-post this issue on his repo :wink: Good luck!

**Comment by mank319** [comment]
@Philip-Scott he actually has write access to *this* repository, so you didn't post to the wrong one. I just wanted to make sure, he is highlighted 😉

**Comment by JMoerman** [comment]
This may not be my repository, but I do get notifications for all issues and development happens here.

AppCenter is definitely something I have to look into later, but I currently don't really have any time to spare.
Elementary OS is my primary OS on both my desktop and laptop, and I do follow the project on g+, but I don't know anything about setting this up, yet. (I didn't contribute to the fundraiser because I haven't got a credit card.)

I just looked at https://developer.elementary.io/dashboard and it seems that I can't add it to this repo, just to my personal repositories.
I guess creating a new public organisation and transferring _Go For It!_ to it would work.

**Comment by JMoerman** [comment]
@Philip-Scott I'll be sure to let you know if I need any help. It may take a while before I start working on it, though.

**Comment by cassidyjames** [comment]
Chiming in as I'd also really love to see Go For It! in AppCenter. I've used it from the PPA and it's a great app.

**Comment by JMoerman** [comment]
@cassidyjames Could you tell me what would be the best way to get _Go For It!_ in AppCenter, as I'm a maintainer, but not the owner of this repository. I just looked at https://developer.elementary.io/dashboard again, and I could select my (out of date) fork now, but I don't know if that's a good idea. Would transferring the repository to an organization (or to me, but the same problem could repeat itself when I would be unable to work on the project.) be a better idea?

I will be on holidays for a while, so it will probably take some time for me to get around to work on it.

**Comment by cassidyjames** [comment]
@JMoerman an organization is likely your best bet! That way you can maintain membership to that org and the namespace of the project (which for now is dependent on the owner + repo name) doesn't change if maintainership changes down the road.

**Comment by JMoerman** [comment]
This issue is now tracked here: https://github.com/JMoerman/Go-For-It/issues/40

**Comment by JMoerman** [comment]
_Go For It!_ is now available on AppCenter.
