### ISSUE TITLE
[Feature request] Use that DnD list widget

### ISSUE THREAD

**Issue by gavr123456789** [mank319/Go-For-It#141]
https://gitlab.com/doublehourglass/dnd_order_list_box 
would looks better and keyboard shortcuts

**Comment by JMoerman** [comment]
Keyboard shortcuts are supported since 1.8 and I don't think that the current drag and drop widget looks too bad:
![Current drag and drop listbox widget](https://user-images.githubusercontent.com/11899523/96768227-e7a54400-13dd-11eb-95e3-de91fabe68ed.gif)
The linked widget lacks functionality such as keeping the positions of the rows synchronized with a model. This means that replacing the current widget with the one you linked would take more effort compared to just improving the current one.
For the user remappable keyboard shortcuts that gitlab repo was actually used as a starting point.

I'm closing this issue as "replace component" isn't a useful issue. If there is something specific you want to look better and can describe how you think it should look and behave: feel free to create a new issue.
(If you do create a new issue please post it here: https://github.com/JMoerman/Go-For-It as I like to have all issues at a centralized place. I'm the maintainer of this application and I can push to this repo, but I'm not the owner of this repo. Some nice/important things I just cannot use here. For example: continuous integration and publishing of application updates to the elementary OS AppCenter.)
