### ISSUE TITLE
Log timer to done.txt

### ISSUE THREAD

**Issue by visit1985** [mank319/Go-For-It#49]
Feature request:

Store the timer value in done.txt when one marks a task as done and display its value in the done panel.

This would make it 100% useful for me :smile:

Awesome tool! Thanks!

**Comment by mank319** [comment]
Thanks for sharing your idea @visit1985. 
Time tracker integration is planned already, but not for storing it in done.txt, because I do not think Todo.txt supports that by any means. It will therefore be a feature that will be integrated in a version that has a more flexible storage backend, which will probably take quite a while.

**Comment by visit1985** [comment]
Thanks for your answer. Actually I think that storung as .txt by default is a neat feature too, because it can easily be shared/synced/version-controlled. Would be nice if it stays.

Off-Topic: Have you thought about storing this values in a separate file using some fuzzy line hashing algorythm to refer the todo.txt? - just a quick thought

**Comment by Asherehsa** [comment]
Are there more details on how time tracker might work? I wasn't thinking about storing the timer value but think it would be very useful to keep track of the number 25 minute blocks you've done for each task. Something like: https://github.com/metalelf0/pomodori-todo.txt

**Comment by JMoerman** [comment]
This could be implemented in the todo.txt format, see: https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format#add-on-file-format-definitions . A task could look like: "(B) 2015-05-15 sometask timer:00:12:34 +testing". The spec doesn't say where the extra information should be stored, though. (in front of contexts/projects or after?)

I'm working on a better parser right now so Go For It can support contexts, priority, creation and completion date and projects.

**Comment by mank319** [comment]
@JMoerman a more advanced parser is definitely important and would be a much appreciated addition! Time tracking, as you described it, would be a good solution for the time being.

One reason to strive for a more flexible storage backend is that it would be nice to have a list with start and end times per task as opposed to one total time. This information could be exported to CSV or visualized somehow, which might be important for people who use time tracking to provide an overview of their work's progress to their customers.

**Comment by JMoerman** [comment]
@mank319 the parser is more or less finished, it can always be extended to support more features later.

The only big problem right now is that it is totally incompatible with the current TaskStore :| . (I turned the tasks into objects)
Any idea's on what task data to display and how to display it?

As for start and end times, we do have creation and completion times, it may not be quite the same, but it is something.

**Comment by mank319** [comment]
@JMoerman I never planned to solely rely on `Gtk.ListStore` as a task list representation and always had a set of "handcrafted model classes" in mind for a later version. So this is not an issue, but a welcome change. This is kind of what I meant when I said "different storage backend": A more complex model structure and a means of making it persistent. Then one could still optionally save a subset of the information available to the Todo.txt file.I will create an issue for discussing details of this new approach.

By the way sorry for the late response. I am currently in the middle of my bachelor's thesis :wink:

**Comment by sductor** [comment]
I believe this would be a great enhancement.
I believe that this could be done easily by only stroing the information on the todo.txt file.
The main advantage of Go For it over other gtd tools is its great simplicity, and I believe that this simple interface should be left as if.
I believe it could be easy to add the date information in the todo.txt when the task is created the end information when it is marked as done and update a field «elapsedtime:timeinmin» every time the ticker is stopped or end.

This would require to update the Filter.vala class in order to parse this information (allowing to write or update it om the text file while ignoring them on the construction of the objects), to add a writing action in the setters of title and done in the TodoTask.vala object as well as in the setters «end_iteration» and stop of TaskTimer using the method  get_runtime

Even though I never used vala, I would be happy to contribute, as it would make goforit the absoulte perfect tool for me. However, I can find the piece of code were you are actually manipulating the files… Would you mind providing some indications?

Regards
Sylvain

**Comment by JMoerman** [comment]
The total time spent working on a task can now be stored in the todo.txt files. It is not yet displayed however.
