### ISSUE TITLE
Task name wrapping

### ISSUE THREAD

**Issue by rustedwolf** [mank319/Go-For-It#65]
Sometimes task name is just too long, so it pushes second column to side and a scrollbar at the bottom appears.
Can we expect some task name wrapping on/off feature?

**Comment by mank319** [comment]
You definitely can expect that to happen as I would love to see that feature too. I will however not find any time for free time development during this month... I will let you know when I start working on it 😉

**Comment by JMoerman** [comment]
Adding

    text_cell.wrap_width = 240;
    text_cell.wrap_mode = Pango.WrapMode.WORD_CHAR;

to TaskList.vala gets you some basic wrapping.
A side effect of this is that some horizontal space is reserved for when the column is at its minimum width (~240 here), so if you expand the window you wont get this horizontal space back.

This could be fixed by updating text_cell.wrap_width whenever the treeview is re-sized, but you would need some way to know the available space for the text column.

(This doesn't fix the issue of the window re-sizing when you click on a task with a very long name...)

**Comment by JMoerman** [comment]
This is fixed in 1.6.0
