### ISSUE TITLE
Please make remaining time visible in Unity and Gnome Shell

### ISSUE THREAD

**Issue by puinenveturi** [mank319/Go-For-It#71]
It would be a nice enhancement to display the time on the Unity and Gnome Shell panel, so the user has it alwasy before the eyes :) A similar feature is implemented in the Pomodoro Gnome Shell extension.

**Comment by vladvran** [comment]
Yes, I would also like to have some sort of notification or indicator in the panel.

**Comment by mank319** [comment]
I considered transforming the main window into a small, floating "always on top widget" that displays only the task name and time, after clicking start.
What would you think about this approach? The advantage is, that it does not rely on features of a particular desktop environment, otherwise I will end up implementing the same feature multiple times...

**Comment by JMoerman** [comment]
> The advantage is, that it does not rely on features of a particular desktop environment, otherwise I will end up implementing the same feature multiple times...

If we are to implement plugin support, this may not actually be a big issue.
A environment specific plugin should be relatively easy to write for something like this.
(I personally like to keep my desktop clutter free, extra windows are not something I would like.)

**Comment by JMoerman** [comment]
Implemented in f300ebd3af41815b07799c90640f98c5240cc05f (plugin, requires libunity). To get it to work Gnome: this should work in combination with dash-to-dock.
