### ISSUE TITLE
Synchronization question

### ISSUE THREAD

**Issue by Opennat** [mank319/Go-For-It#81]
I use Simpletask (cloudless version - https://github.com/mpcjanssen/simpletask-android) on Android with Syncthing (https://github.com/syncthing/syncthing) to sync between Simpletask and Go For It. Sync does well, but GFI does not refresh todo.txt after sync, and get new tasks only after manual "Settings->Refresh" or via restart. Shouldn't GFI reload todo.txt automatically after changes to it happens?

**Comment by mank319** [comment]
Implemented the desired behaviour using a `FileMonitor`.
Appears to work fine - please tell me, if you encounter any issues :wink:

**Comment by JMoerman** [comment]
It isn't quite as simple as that:
* saving will cause the monitor to emit the changed signal, causing several refreshes after saving.
* The reference to the active task used by TaskTimer will no longer be valid, you will need to scan todo_store for the task and update the TaskTimer accordingly.

(Also: what happens when you finish a task in a TaskList while TaskTimer is running with the same task? Yes, the reference will no longer be valid.)

I've been fixing issues like these in my wip branch, but I haven't ported all of the fixes back because of a lack of time.

**Comment by mank319** [comment]
@JMoerman you made a few fair points there :wink: 

As for the reference no longer being valid, the same problem already exists if you edit tasks from within *Go For It* while the timer is running and might require a "manual refresh" of the active task by (re)selecting a task in the list.

I have checked what you said about the refresh procedure and I have to say it appears to be true that the refresh is triggered multiple times (25 in my case) whenever you change something from within the application.
I would expect it to refresh once (that would be perfectly fine, imho) but I do not have an explanation for this, as there are no cycles involved. Nothing gets written to disk during refresh to re-trigger the event - or have I missed something?

It could be solved this with a simple timestamp approach: "Do not refresh if the last save was less then *x* microseconds ago".
However, this feels like a hack to me and for now even refreshing 25 times does not have a recognizable practical impact on the usability of the app (at least not on my machine), so it should be safe to leave it in that state until we actually merge your wip branch and restructure many things anyway. Do you agree?

**Comment by JMoerman** [comment]
@mank319 I agree.

As for the issues: Yes, you have missed:
* That loading files causes saves, but only if it is caused by a refresh.
* That a FileMonitor is mean and emits several events per change.

Lets start with loading: for every task that is added the signal task_data_changed is emitted, which in turn causes save_tasks to be called. (If you have 5 tasks you will load once followed by 5 saves.)
Every save could potentially be noticed by monitor, causing additional loads.
Also just editing a task does not cause the reference to change, this is caused by a refresh triggered by saving. The title used by TimerView wouldn't be updated though.
