### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by beli3ver** [mank319/Go-For-It#96]
Hi

I have done the german translation:

https://translations.launchpad.net/go-for-it

**Comment by JMoerman** [comment]
Thanks for translating!
![schermafdruk van 2016-11-22 13 44 28](https://cloud.githubusercontent.com/assets/11899523/20524252/e6260f32-b0b9-11e6-9c6a-b26ee82423d7.png)

Expect to be able to use it next update.

**Comment by beli3ver** [comment]
When do you make the release with the translation ?

**Comment by JMoerman** [comment]
I expect within a week. I want to fix/implement a few more things first.

**Comment by JMoerman** [comment]
Sorry for my late response, I haven't had much time and energy due to deadlines, not sleeping to well, a mild flu and some other stuff.
I have no control over the old ppa and the old ppa needed to be updated manualy. I created a new ppa that should be updated once a day if the source has been updated: https://launchpad.net/~go-for-it-team/+archive/ubuntu/go-for-it-daily
If you use Debian/Ubuntu or a an OS based on either of those, you can get an updated build using that ppa.
I still need to bump the version and make a new release so the version is still 1.4.7.
